services:
  vllm_app:
    image: vllm/vllm-openai:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    command: >
      --host ${HOST}
      --model "${BASE_MODEL}"
      --lora-modules "${SAT_LORA_MODEL_NAME}"="${LORA_MODEL}"
      --max-model-len ${MAX_MODEL_LEN}
      --enable-lora
      --enable-prefix-caching
    ports:
      - "${VLLM_PORT}:${VLLM_PORT}"
    ipc: host
    environment:
      - VLLM_ALLOW_RUNTIME_LORA_UPDATING=True
    networks:
      - sat-network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "${OPEN_WEBUI_PORT}:${OPEN_WEBUI_PORT}"
    env_file:
      - .env
    depends_on:
      - vllm_app
    networks:
      - sat-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    depends_on:
      - vllm_app
    networks:
      - sat-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - sat-network

networks:
  sat-network: