services:
  vllm_app:
    image: vllm/vllm-openai:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    command: >
      --host ${HOST}
      --model "${BASE_MODEL}"
      --lora-modules "${SAT_LORA_MODEL_NAME}"="${LORA_MODEL}"
      --max-model-len 2048
      --enable-lora
      --enable-prefix-caching
    ports:
      - "${VLLM_PORT}:${VLLM_PORT}"
    ipc: host
    environment:
      - VLLM_ALLOW_RUNTIME_LORA_UPDATING=True

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "${OPEN_WEBUI_PORT}:${OPEN_WEBUI_PORT}"
    environment:
      - 'OPENAI_API_BASE_URL=${VLLM_API_BASE_URL}'
      - 'OPENAI_API_KEY=${VLLM_API_KEY}'
    depends_on:
      - vllm_app
    extra_hosts:
      - "host.docker.internal:host-gateway"